site_name: 2025 Cisco Live LTRCOM-2000 Lab Guide
site_url: https://nmortari.github.io/LTRCOM-2000/
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    # - navigation.expand
    - navigation.sections
    - toc.follow

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  #- Disclaimer:
  #  - Disclaimer/index.md
  #- Scenario:
  #  - Scenario/index.md
  #- Network Diagram:
  #  - NetworkDiagram/index.md
  #- Connecting to the Lab Components:
  #  - Connect to Intersight: LabComponents/1-ConnectToIntersight.md
  #  - Command Palette / User Label: LabComponents/2-CommandPaletteUserLabel.md

  - Instructions:
    - Disclaimer:
      - Disclaimer/index.md
    - Scenario:
      - Scenario/index.md
    - Network Diagram:
      - NetworkDiagram/index.md
    - Connecting to the Lab Components:
      - LabComponents/ConnectToIntersight.md
      - LabComponents/CommandPaletteUserLabel.md
    - Templates and Cloning:
      - TemplatesAndCloning/Introduction.md
      - TemplatesAndCloning/Cloning.md
      - TemplatesAndCloning/VerifyTheNewlyCreatedClone.md
      - TemplatesAndCloning/ChangeTheUCSServerProfileTemplate.md
      - TemplatesAndCloning/CreateUCSServerProfileFromTemplate.md
    - Repository:
      - Repository/index.md
    - Automation:
      - Automation/Introduction.md
      - Automation/CreateANewWorkflow.md
      - Automation/ComposeTheWorkflow.md
      - Automation/ExecuteTheWorkflow.md
    - Time For A Break:
      - TimeForABreak/index.md
    - Server Inventory:
      - ServerInventory/index.md
    - Troubleshooting:
      - Troubleshooting/Introduction.md
      - Troubleshooting/ConnectToVPN.md
      - Troubleshooting/GetTheOSIPAndStartAPing.md
      - Troubleshooting/BladeRediscovery.md
      - Troubleshooting/DecommissionAndRecommission.md
      - Troubleshooting/PowerCycleChassisSlot.md
      - Troubleshooting/RebootManagementController.md
      - Troubleshooting/TestingVNICFailover.md
    - Metrics:
      - Metrics/Introduction.md
      - Metrics/ServerMetrics.md
      - Metrics/Explorer.md
    - Related Sessions At Cisco Live:
      - RelatedSessionsAtCiscoLive/index.md