site_name: 2025 Cisco Live LTRCOM-2000 Lab Guide
site_url: https://nmortari.github.io/LTRCOM-2000/
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - toc.follow

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Lab Guide:
    - labguide.md
    - Disclaimer:
      - Disclaimer/index.md
    - Scenario:
      - Scenario/index.md
    - Network Diagram: NetworkDiagram.md
    - Connecting to the Lab Components:
      - labcomponents/ConnectToIntersight.md
      - labcomponents/CommandPalleteUserLabel.md