site_name: My MkDocs Material Documentation Test
site_url: https://sitename.example
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: light blue
  font:
    text: Merriweather Sans
    code: Red Hat Mono